/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.validation;

import it.polimi.ase.projectB2.team20.xtext.validation.AbstractFashionDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FashionDslValidator extends AbstractFashionDslValidator {
}
