/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.fashionDsl.impl;

import it.polimi.ase.projectB2.team20.xtext.fashionDsl.Choreographer;
import it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Choreographer</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ChoreographerImpl extends RoleImpl implements Choreographer
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChoreographerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FashionDslPackage.Literals.CHOREOGRAPHER;
  }

} //ChoreographerImpl
