/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.fashionDsl.impl;

import it.polimi.ase.projectB2.team20.xtext.fashionDsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class FashionDslFactoryImpl extends EFactoryImpl implements FashionDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static FashionDslFactory init()
  {
    try
    {
      FashionDslFactory theFashionDslFactory = (FashionDslFactory)EPackage.Registry.INSTANCE.getEFactory(FashionDslPackage.eNS_URI);
      if (theFashionDslFactory != null)
      {
        return theFashionDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new FashionDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FashionDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case FashionDslPackage.FASHION_DOMAIN: return createFashionDomain();
      case FashionDslPackage.FASHION_ELEMENT: return createFashionElement();
      case FashionDslPackage.BRAND: return createBrand();
      case FashionDslPackage.NEWS_REPORT: return createNewsReport();
      case FashionDslPackage.REVIEW: return createReview();
      case FashionDslPackage.ROLE: return createRole();
      case FashionDslPackage.REVIEWER: return createReviewer();
      case FashionDslPackage.EVENT: return createEvent();
      case FashionDslPackage.FASHION_STYLE: return createFashionStyle();
      case FashionDslPackage.SPATIO_TEMPORAL_DESCRIPTOR: return createSpatioTemporalDescriptor();
      case FashionDslPackage.ARTICLE: return createArticle();
      case FashionDslPackage.TV_PROGRAM: return createTVProgram();
      case FashionDslPackage.FAMOUS_BRAND: return createFamousBrand();
      case FashionDslPackage.EMERGING_BRAND: return createEmergingBrand();
      case FashionDslPackage.LOCAL_BRAND: return createLocalBrand();
      case FashionDslPackage.ADVERTISING_CAMPAIGN: return createAdvertisingCampaign();
      case FashionDslPackage.ADVERTISING_PRODUCT: return createAdvertisingProduct();
      case FashionDslPackage.PRODUCT_LINE: return createProductLine();
      case FashionDslPackage.PRODUCT_STYLE: return createProductStyle();
      case FashionDslPackage.PRODUCT: return createProduct();
      case FashionDslPackage.PHOTO: return createPhoto();
      case FashionDslPackage.DESCRIPTION: return createDescription();
      case FashionDslPackage.COMMENT: return createComment();
      case FashionDslPackage.BLOGGER: return createBlogger();
      case FashionDslPackage.CRITIC: return createCritic();
      case FashionDslPackage.INFLUENCER: return createInfluencer();
      case FashionDslPackage.DESIGNER: return createDesigner();
      case FashionDslPackage.MODEL: return createModel();
      case FashionDslPackage.PHOTOGRAPHER: return createPhotographer();
      case FashionDslPackage.CHOREOGRAPHER: return createChoreographer();
      case FashionDslPackage.PRESENTER: return createPresenter();
      case FashionDslPackage.MACRO_EVENT: return createMacroEvent();
      case FashionDslPackage.SINGLE_BRAND_EVENT: return createSingleBrandEvent();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FashionDomain createFashionDomain()
  {
    FashionDomainImpl fashionDomain = new FashionDomainImpl();
    return fashionDomain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FashionElement createFashionElement()
  {
    FashionElementImpl fashionElement = new FashionElementImpl();
    return fashionElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Brand createBrand()
  {
    BrandImpl brand = new BrandImpl();
    return brand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NewsReport createNewsReport()
  {
    NewsReportImpl newsReport = new NewsReportImpl();
    return newsReport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Review createReview()
  {
    ReviewImpl review = new ReviewImpl();
    return review;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Role createRole()
  {
    RoleImpl role = new RoleImpl();
    return role;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Reviewer createReviewer()
  {
    ReviewerImpl reviewer = new ReviewerImpl();
    return reviewer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event createEvent()
  {
    EventImpl event = new EventImpl();
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FashionStyle createFashionStyle()
  {
    FashionStyleImpl fashionStyle = new FashionStyleImpl();
    return fashionStyle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SpatioTemporalDescriptor createSpatioTemporalDescriptor()
  {
    SpatioTemporalDescriptorImpl spatioTemporalDescriptor = new SpatioTemporalDescriptorImpl();
    return spatioTemporalDescriptor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Article createArticle()
  {
    ArticleImpl article = new ArticleImpl();
    return article;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TVProgram createTVProgram()
  {
    TVProgramImpl tvProgram = new TVProgramImpl();
    return tvProgram;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FamousBrand createFamousBrand()
  {
    FamousBrandImpl famousBrand = new FamousBrandImpl();
    return famousBrand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EmergingBrand createEmergingBrand()
  {
    EmergingBrandImpl emergingBrand = new EmergingBrandImpl();
    return emergingBrand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LocalBrand createLocalBrand()
  {
    LocalBrandImpl localBrand = new LocalBrandImpl();
    return localBrand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AdvertisingCampaign createAdvertisingCampaign()
  {
    AdvertisingCampaignImpl advertisingCampaign = new AdvertisingCampaignImpl();
    return advertisingCampaign;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AdvertisingProduct createAdvertisingProduct()
  {
    AdvertisingProductImpl advertisingProduct = new AdvertisingProductImpl();
    return advertisingProduct;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProductLine createProductLine()
  {
    ProductLineImpl productLine = new ProductLineImpl();
    return productLine;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProductStyle createProductStyle()
  {
    ProductStyleImpl productStyle = new ProductStyleImpl();
    return productStyle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Product createProduct()
  {
    ProductImpl product = new ProductImpl();
    return product;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Photo createPhoto()
  {
    PhotoImpl photo = new PhotoImpl();
    return photo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Description createDescription()
  {
    DescriptionImpl description = new DescriptionImpl();
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Comment createComment()
  {
    CommentImpl comment = new CommentImpl();
    return comment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Blogger createBlogger()
  {
    BloggerImpl blogger = new BloggerImpl();
    return blogger;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Critic createCritic()
  {
    CriticImpl critic = new CriticImpl();
    return critic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Influencer createInfluencer()
  {
    InfluencerImpl influencer = new InfluencerImpl();
    return influencer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Designer createDesigner()
  {
    DesignerImpl designer = new DesignerImpl();
    return designer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Photographer createPhotographer()
  {
    PhotographerImpl photographer = new PhotographerImpl();
    return photographer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Choreographer createChoreographer()
  {
    ChoreographerImpl choreographer = new ChoreographerImpl();
    return choreographer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Presenter createPresenter()
  {
    PresenterImpl presenter = new PresenterImpl();
    return presenter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MacroEvent createMacroEvent()
  {
    MacroEventImpl macroEvent = new MacroEventImpl();
    return macroEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SingleBrandEvent createSingleBrandEvent()
  {
    SingleBrandEventImpl singleBrandEvent = new SingleBrandEventImpl();
    return singleBrandEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FashionDslPackage getFashionDslPackage()
  {
    return (FashionDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static FashionDslPackage getPackage()
  {
    return FashionDslPackage.eINSTANCE;
  }

} //FashionDslFactoryImpl
