/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.fashionDsl.impl;

import it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage;
import it.polimi.ase.projectB2.team20.xtext.fashionDsl.Product;
import it.polimi.ase.projectB2.team20.xtext.fashionDsl.Review;
import it.polimi.ase.projectB2.team20.xtext.fashionDsl.Reviewer;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Review</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.impl.ReviewImpl#getProduct <em>Product</em>}</li>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.impl.ReviewImpl#getReviewer <em>Reviewer</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReviewImpl extends FashionElementImpl implements Review
{
  /**
   * The cached value of the '{@link #getProduct() <em>Product</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProduct()
   * @generated
   * @ordered
   */
  protected Product product;

  /**
   * The cached value of the '{@link #getReviewer() <em>Reviewer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReviewer()
   * @generated
   * @ordered
   */
  protected Reviewer reviewer;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReviewImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FashionDslPackage.Literals.REVIEW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Product getProduct()
  {
    if (product != null && product.eIsProxy())
    {
      InternalEObject oldProduct = (InternalEObject)product;
      product = (Product)eResolveProxy(oldProduct);
      if (product != oldProduct)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FashionDslPackage.REVIEW__PRODUCT, oldProduct, product));
      }
    }
    return product;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Product basicGetProduct()
  {
    return product;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProduct(Product newProduct)
  {
    Product oldProduct = product;
    product = newProduct;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FashionDslPackage.REVIEW__PRODUCT, oldProduct, product));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Reviewer getReviewer()
  {
    if (reviewer != null && reviewer.eIsProxy())
    {
      InternalEObject oldReviewer = (InternalEObject)reviewer;
      reviewer = (Reviewer)eResolveProxy(oldReviewer);
      if (reviewer != oldReviewer)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FashionDslPackage.REVIEW__REVIEWER, oldReviewer, reviewer));
      }
    }
    return reviewer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Reviewer basicGetReviewer()
  {
    return reviewer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReviewer(Reviewer newReviewer)
  {
    Reviewer oldReviewer = reviewer;
    reviewer = newReviewer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FashionDslPackage.REVIEW__REVIEWER, oldReviewer, reviewer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FashionDslPackage.REVIEW__PRODUCT:
        if (resolve) return getProduct();
        return basicGetProduct();
      case FashionDslPackage.REVIEW__REVIEWER:
        if (resolve) return getReviewer();
        return basicGetReviewer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FashionDslPackage.REVIEW__PRODUCT:
        setProduct((Product)newValue);
        return;
      case FashionDslPackage.REVIEW__REVIEWER:
        setReviewer((Reviewer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FashionDslPackage.REVIEW__PRODUCT:
        setProduct((Product)null);
        return;
      case FashionDslPackage.REVIEW__REVIEWER:
        setReviewer((Reviewer)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FashionDslPackage.REVIEW__PRODUCT:
        return product != null;
      case FashionDslPackage.REVIEW__REVIEWER:
        return reviewer != null;
    }
    return super.eIsSet(featureID);
  }

} //ReviewImpl
