/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.ui;

import it.polimi.ase.projectB2.team20.xtext.ui.AbstractFashionDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FashionDslUiModule extends AbstractFashionDslUiModule {
  public FashionDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
