/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext;

import it.polimi.ase.projectB2.team20.xtext.AbstractFashionDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FashionDslRuntimeModule extends AbstractFashionDslRuntimeModule {
}
