/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext;

import it.polimi.ase.projectB2.team20.xtext.FashionDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FashionDslStandaloneSetup extends FashionDslStandaloneSetupGenerated {
  public static void doSetup() {
    new FashionDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
