/*
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FashionDslStandaloneSetup extends FashionDslStandaloneSetupGenerated {

	def static void doSetup() {
		new FashionDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
