/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.scoping;

import it.polimi.ase.projectB2.team20.xtext.scoping.AbstractFashionDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FashionDslScopeProvider extends AbstractFashionDslScopeProvider {
}
