/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.fashionDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Brand</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.Brand#getStyles <em>Styles</em>}</li>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.Brand#getReports <em>Reports</em>}</li>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.Brand#getCampaigns <em>Campaigns</em>}</li>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.Brand#getProductlines <em>Productlines</em>}</li>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.Brand#getDesigners <em>Designers</em>}</li>
 * </ul>
 *
 * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getBrand()
 * @model
 * @generated
 */
public interface Brand extends FashionElement
{
  /**
   * Returns the value of the '<em><b>Styles</b></em>' reference list.
   * The list contents are of type {@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionStyle}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Styles</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Styles</em>' reference list.
   * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getBrand_Styles()
   * @model
   * @generated
   */
  EList<FashionStyle> getStyles();

  /**
   * Returns the value of the '<em><b>Reports</b></em>' containment reference list.
   * The list contents are of type {@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.NewsReport}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reports</em>' containment reference list.
   * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getBrand_Reports()
   * @model containment="true"
   * @generated
   */
  EList<NewsReport> getReports();

  /**
   * Returns the value of the '<em><b>Campaigns</b></em>' reference list.
   * The list contents are of type {@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.AdvertisingCampaign}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Campaigns</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Campaigns</em>' reference list.
   * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getBrand_Campaigns()
   * @model
   * @generated
   */
  EList<AdvertisingCampaign> getCampaigns();

  /**
   * Returns the value of the '<em><b>Productlines</b></em>' reference list.
   * The list contents are of type {@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.ProductLine}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Productlines</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Productlines</em>' reference list.
   * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getBrand_Productlines()
   * @model
   * @generated
   */
  EList<ProductLine> getProductlines();

  /**
   * Returns the value of the '<em><b>Designers</b></em>' reference list.
   * The list contents are of type {@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.Designer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Designers</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Designers</em>' reference list.
   * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getBrand_Designers()
   * @model
   * @generated
   */
  EList<Designer> getDesigners();

} // Brand
