/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.fashionDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Designer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.Designer#getBrand <em>Brand</em>}</li>
 * </ul>
 *
 * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getDesigner()
 * @model
 * @generated
 */
public interface Designer extends Role
{
  /**
   * Returns the value of the '<em><b>Brand</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Brand</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Brand</em>' reference.
   * @see #setBrand(Brand)
   * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getDesigner_Brand()
   * @model
   * @generated
   */
  Brand getBrand();

  /**
   * Sets the value of the '{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.Designer#getBrand <em>Brand</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Brand</em>' reference.
   * @see #getBrand()
   * @generated
   */
  void setBrand(Brand value);

} // Designer
