/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.fashionDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Emerging Brand</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.EmergingBrand#getCountries <em>Countries</em>}</li>
 * </ul>
 *
 * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getEmergingBrand()
 * @model
 * @generated
 */
public interface EmergingBrand extends Brand
{
  /**
   * Returns the value of the '<em><b>Countries</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Countries</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Countries</em>' attribute.
   * @see #setCountries(String)
   * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getEmergingBrand_Countries()
   * @model
   * @generated
   */
  String getCountries();

  /**
   * Sets the value of the '{@link it.polimi.ase.projectB2.team20.xtext.fashionDsl.EmergingBrand#getCountries <em>Countries</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Countries</em>' attribute.
   * @see #getCountries()
   * @generated
   */
  void setCountries(String value);

} // EmergingBrand
