/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.fashionDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Presenter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getPresenter()
 * @model
 * @generated
 */
public interface Presenter extends Role
{
} // Presenter
