/**
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.fashionDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Product Style</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.polimi.ase.projectB2.team20.xtext.fashionDsl.FashionDslPackage#getProductStyle()
 * @model
 * @generated
 */
public interface ProductStyle extends FashionElement
{
} // ProductStyle
