/*
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.ui.tests;

import com.google.inject.Injector;
import it.polimi.ase.projectB2.team20.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class FashionDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("it.polimi.ase.projectB2.team20.xtext.FashionDsl");
	}

}
