/*
 * generated by Xtext 2.10.0
 */
package it.polimi.ase.projectB2.team20.xtext.parser.antlr;

import com.google.inject.Inject;
import it.polimi.ase.projectB2.team20.xtext.parser.antlr.internal.InternalFashionDslParser;
import it.polimi.ase.projectB2.team20.xtext.services.FashionDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FashionDslParser extends AbstractAntlrParser {

	@Inject
	private FashionDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFashionDslParser createParser(XtextTokenStream stream) {
		return new InternalFashionDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FashionDomain";
	}

	public FashionDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FashionDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
