<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fashion" nsURI="http://fashion.it" nsPrefix="ase.projectB.team20.fashion">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="FashionDomain">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//FashionElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" lowerBound="1"
        upperBound="-1" eType="#//FashionStyle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FashionElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" upperBound="-1"
        eType="#//FashionStyle" eOpposite="#//FashionStyle/elements">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reports" upperBound="-1"
        eType="#//NewsReport" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewsReport" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//MediaType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//FashionElement">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article" eSuperTypes="#//NewsReport">
    <eAnnotations source="gmf.node">
      <details key="label" value="title,type"/>
      <details key="label.pattern" value="{1}: {0}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magazine" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TVProgram" eSuperTypes="#//NewsReport">
    <eAnnotations source="gmf.node">
      <details key="label" value="name,type"/>
      <details key="label.pattern" value="{1}: {0}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FashionStyle">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptors" lowerBound="1"
        upperBound="-1" eType="#//SpatioTemporalDescriptor" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//FashionElement" eOpposite="#//FashionElement/styles">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpatioTemporalDescriptor">
    <eAnnotations source="gmf.node">
      <details key="label" value="period,location"/>
      <details key="label.pattern" value="{0}, {1}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Brand" abstract="true" eSuperTypes="#//FashionElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campaigns" upperBound="-1"
        eType="#//AdvertisingCampaign" eOpposite="#//AdvertisingCampaign/brand">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productLines" lowerBound="1"
        upperBound="-1" eType="#//ProductLine" eOpposite="#//ProductLine/brand">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designers" lowerBound="1"
        upperBound="-1" eType="#//Designer" eOpposite="#//Designer/brand">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamousBrand" eSuperTypes="#//Brand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="countries" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmergingBrand" eSuperTypes="#//Brand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="countries" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalBrand" eSuperTypes="#//Brand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdvertisingCampaign" eSuperTypes="#//FashionElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brand" lowerBound="1" eType="#//Brand"
        eOpposite="#//Brand/campaigns">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" lowerBound="1"
        upperBound="-1" eType="#//AdvertisingProduct" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdvertisingProduct" eSuperTypes="#//FashionElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name,type"/>
      <details key="label.pattern" value="{0}: {1}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//MediaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//FashionElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/events">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MacroEvent" eSuperTypes="#//Event">
    <eAnnotations source="gmf.node">
      <details key="label" value="name,year,month,city"/>
      <details key="label.pattern" value="{0}, {1}-{2}, {3}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleBrandEvents" lowerBound="1"
        upperBound="-1" eType="#//SingleBrandEvent" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleBrandEvent" eSuperTypes="#//Event">
    <eAnnotations source="gmf.node">
      <details key="label" value="name,year,month,day,hour,minute"/>
      <details key="label.pattern" value="{0}, {1}-{2}-{3}, {4}:{5}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minute" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brand" lowerBound="1" eType="#//Brand">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductLine" eSuperTypes="#//FashionElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brand" lowerBound="1" eType="#//Brand"
        eOpposite="#//Brand/productLines">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productStyles" lowerBound="1"
        upperBound="-1" eType="#//ProductStyle" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" lowerBound="1"
        upperBound="-1" eType="#//Product" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductStyle" eSuperTypes="#//FashionElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//FashionElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reviews" upperBound="-1"
        eType="#//Review" eOpposite="#//Review/product">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Review" abstract="true" eSuperTypes="#//FashionElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
        eType="#//Product" eOpposite="#//Product/reviews">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reviewer" lowerBound="1"
        eType="#//Reviewer" eOpposite="#//Reviewer/reviews">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Photo" eSuperTypes="#//Review">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" eSuperTypes="#//Review">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Review">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true" eSuperTypes="#//FashionElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" lowerBound="1"
        upperBound="-1" eType="#//Event" eOpposite="#//Event/roles">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Designer" eSuperTypes="#//Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brand" lowerBound="1" eType="#//Brand"
        eOpposite="#//Brand/designers">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Presenter" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Choreographer" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Photographer" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reviewer" abstract="true" eSuperTypes="#//Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reviews" lowerBound="1"
        upperBound="-1" eType="#//Review" eOpposite="#//Review/reviewer">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Blogger" eSuperTypes="#//Reviewer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Critic" eSuperTypes="#//Reviewer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Influencer" eSuperTypes="#//Reviewer"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MediaType">
    <eLiterals name="Online"/>
    <eLiterals name="TV" value="1"/>
    <eLiterals name="PhysicalBoard" value="2"/>
  </eClassifiers>
</ecore:EPackage>
